import GuestLayouts from "@/Layouts/guest-layouts";
import { Link, Head } from "@inertiajs/react";

export default function Welcome(props) {
    return (
        <GuestLayouts>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section>
                <div
                    className="hero min-h-screen"
                    style={{
                        backgroundImage: `url("/assets/imgs/img1.jpg")`,
                    }}
                >
                    <div className="hero-overlay bg-opacity-60"></div>
                    <div className="hero-content text-center text-neutral-content">
                        <div className="max-w-md">
                            <h1 className="mb-5 text-5xl font-bold">
                                Hello there
                            </h1>
                            <p className="mb-5">
                                Selamat datang di website ini, semoga hari anda
                                bahagia selalu
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        </GuestLayouts>
    );
}
