import LogedLayouts from "@/Layouts/loged-layouts";
import { Head } from "@inertiajs/react";
import React, { useState } from "react";

const Page = (props) => {
    const [selectedKecamatan, setSelectedKecamatan] = useState(null);
    const [selectedJenisPengaduan, setSelectedJenisPengaduan] = useState(null);
    const [form, setForm] = useState(false);

    const handleKecamatanChange = (event) => {
        const selectedKecamatanId = event.target.value;
        const selectedKecamatan = props.data.kecamatan.find(
            (kecamatan) => kecamatan.id === Number(selectedKecamatanId)
        );
        setSelectedKecamatan(selectedKecamatan);
    };

    const handleJenisPengaduanChange = (event) => {
        const selectedJenisPengaduan = event.target.value;
        setSelectedJenisPengaduan(selectedJenisPengaduan);
        selectedJenisPengaduan != 3 ? setForm(true) : setForm(false);
    };

    const getKelurahanOptions = () => {
        if (!selectedKecamatan) {
            return [];
        }
        return selectedKecamatan.kelurahan.map((kelurahan) => (
            <option key={kelurahan.id} value={kelurahan.id}>
                {kelurahan.name}
            </option>
        ));
    };

    console.log(selectedJenisPengaduan);
    return (
        <LogedLayouts>
            <Head>
                <title>Input Pemohon</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className="relative box-border p-5 md:py-20 md:px-10 lg:py-0 w-full">
                <div className="flex flex-wrap p-2 md:p-5 w-full bg-base-200 md:justify-between">
                    <h1 className="md:w-full">Form Input Pengaduan</h1>
                    <div className="form-control w-full max-w-xs">
                        <label className="label">
                            <span className="label-text">Jenis Pengaduan</span>
                        </label>
                        <select
                            className="select select-bordered"
                            onChange={handleJenisPengaduanChange}
                        >
                            <option disabled selected>
                                Jenis Pengaduan
                            </option>
                            {props.data1.map((data, i) => {
                                return (
                                    <option key={i} value={data.id}>
                                        {data.jenis_pengaduan}
                                    </option>
                                );
                            })}
                        </select>
                    </div>
                    <div className="form-control w-full max-w-xs">
                        <label className="label">
                            <span className="label-text">
                                Jenis Media Pengaduan
                            </span>
                        </label>
                        <select className="select select-bordered">
                            <option disabled selected>
                                Jenis Media Pengaduan
                            </option>
                            <option>WhatsApp</option>
                            <option>Sentuh Tanahku</option>
                            <option>Google Form</option>
                        </select>
                    </div>
                    <div className="form-control w-full max-w-xs">
                        <label className="label">
                            <span className="label-text">Nama Pemohon</span>
                        </label>
                        <input
                            type="text"
                            placeholder="Masukkan Nama Pemohon"
                            className="input input-bordered w-full max-w-xs"
                        />
                        <label className="label">
                            <span className="label-text-alt">
                                Bottom Left label
                            </span>
                        </label>
                    </div>
                    {form == true ? (
                        <div className="form-control w-full max-w-xs">
                            <label className="label">
                                <span className="label-text">No KTP</span>
                            </label>
                            <input
                                type="text"
                                placeholder="Masukan NIK Pemohon"
                                className="input input-bordered w-full max-w-xs"
                            />
                            <label className="label">
                                <span className="label-text-alt">
                                    Bottom Left label
                                </span>
                            </label>
                        </div>
                    ) : null}

                    {form == true ? (
                        <div className="form-control w-full max-w-xs">
                            <label className="label">
                                <span className="label-text">No Hak</span>
                            </label>
                            <input
                                type="text"
                                placeholder="Type here"
                                className="input input-bordered w-full max-w-xs"
                            />
                            <label className="label">
                                <span className="label-text-alt">
                                    Bottom Left label
                                </span>
                                <span className="label-text-alt">
                                    <button className="btn btn-info text-base-100">
                                        Validation No Hak
                                    </button>
                                </span>
                            </label>
                        </div>
                    ) : null}
                    {form == true ? (
                        <div className="form-control w-full max-w-xs">
                            <label className="label">
                                <span className="label-text">
                                    Jenis Sertifikat
                                </span>
                            </label>
                            <select className="select select-bordered">
                                <option disabled selected>
                                    Jenis Hak
                                </option>
                                <option>Sertifikat Hak Milik (SHM)</option>
                                <option>Sertifikat Hak Guna Usaha (HGU)</option>
                                <option>Sertifikat Hak Pakai</option>
                                <option>
                                    Sertifikat Hak Guna Bangunan (SHGB)
                                </option>
                            </select>
                        </div>
                    ) : null}
                    <div className="form-control w-full">
                        <label className="label">
                            <span className="label-text">
                                Keterangan Laporan Pengaduan
                            </span>
                        </label>
                        <textarea
                            className="textarea textarea-bordered h-24"
                            placeholder="Keterangan Laporan Pengaduan"
                        />
                    </div>
                    {form == true ? (
                        <div className="form-control flex-row flex-wrap justify-between">
                            <label className="label cursor-pointer space-x-3">
                                <span className="label-text">Seksi 1</span>
                                <input type="checkbox" className="checkbox" />
                            </label>
                            <label className="label cursor-pointer space-x-3">
                                <span className="label-text">Seksi 2</span>
                                <input type="checkbox" className="checkbox" />
                            </label>
                            <label className="label cursor-pointer space-x-3">
                                <span className="label-text">Seksi 3</span>
                                <input type="checkbox" className="checkbox" />
                            </label>
                            <label className="label cursor-pointer space-x-3">
                                <span className="label-text">Seksi 4</span>
                                <input type="checkbox" className="checkbox" />
                            </label>
                            <label className="label cursor-pointer space-x-3">
                                <span className="label-text">Seksi 5</span>
                                <input type="checkbox" className="checkbox" />
                            </label>
                        </div>
                    ) : null}

                    {form == true ? (
                        <div className="form-control w-full max-w-xs">
                            <label className="label">
                                <span className="label-text">Kecamatan</span>
                            </label>
                            <select
                                id="kecamatan"
                                className="select select-bordered"
                                onChange={handleKecamatanChange}
                            >
                                <option disabled selected>
                                    Kecamatan
                                </option>
                                {props.data.kecamatan.map((data, i) => {
                                    return (
                                        <option key={i} value={data.id}>
                                            {data.name}
                                        </option>
                                    );
                                })}
                            </select>
                        </div>
                    ) : null}
                    {form == true ? (
                        <div className="form-control w-full max-w-xs">
                            <label className="label">
                                <span className="label-text">Kelurahan</span>
                            </label>
                            <select
                                id="kelurahan"
                                className="select select-bordered"
                                disabled={!selectedKecamatan}
                            >
                                <option disabled selected>
                                    Kelurahan
                                </option>
                                {getKelurahanOptions()}
                            </select>
                        </div>
                    ) : null}
                    <button className="mt-3 btn btn-info text-base-100">
                        Upload
                    </button>
                </div>
            </section>
        </LogedLayouts>
    );
};

export default Page;
